/**
 * ------------------------------------------------------------------
 *  Title    |  Lab routes
 *  Ref      |  DESIGN.md §1.4, §4.1
 *  ID       |  core
 * ------------------------------------------------------------------
 *  Purpose  |  Start a lab run from one of your messages, see what it
 *           |  changed, and undo it.
 *  How      |  A lab answer is an assistant reply like any other (it
 *           |  sits in the tree, can be regenerated by chat, branched),
 *           |  written by an `agent` run instead of a `chat_turn`.
 *           |  Undo puts back the folder as it was before that run, so
 *           |  it is only offered while nothing has happened since: no
 *           |  run is live in the thread, no later lab run exists, and
 *           |  this one has not been undone already.
 * ------------------------------------------------------------------
 */

import { AncileError } from '@nvx/contracts';
import { Hono } from 'hono';
import { ulid } from 'ulid';
import type { AppEnv } from '../app';
import { currentContext, newTraceId } from '../context';
import { notFound } from '../obs/errors';
import type { RunStore } from '../runs/engine';
import { alreadyRunning } from '../runs/store';
import type { RunWorker } from '../runs/worker';
import { type ThreadRepo, textOf } from '../threads/repo';
import type { Engine } from './engine-client';
import { type LabCheckpoint, labPlace, snapshotDir } from './handler';
import { diffSnapshot, restoreSnapshot, snapshotUsable } from './snapshot';

export interface LabRouteDeps {
  engine: Engine | null;
  repo: ThreadRepo;
  runs: RunStore;
  worker: Pick<RunWorker, 'kick'>;
  workspaceId: string;
  workspaceDir: string;
  workspaceRoot: string;
  snapshotsDir: string;
}

export const labUnavailable = () =>
  new AncileError({
    code: 'lab.unavailable',
    title: "The lab isn't running",
    hint: 'It needs Bun (https://bun.sh). Install it, then restart Ancile with pnpm start.',
    status: 503,
    errorClass: 'transient',
  });

const undoRefused = (code: string, title: string, hint: string) =>
  new AncileError({ code, title, hint, status: 409, errorClass: 'permanent' });

export function labRoutes(deps: LabRouteDeps) {
  const r = new Hono<AppEnv>();
  /** Undos in progress, so two clicks cannot restore twice. */
  const undoing = new Set<string>();

  const labRun = async (id: string) => {
    const run = await deps.runs.get(id);
    if (run?.kind !== 'agent') throw notFound('That lab run');
    const cp = run.checkpoint as LabCheckpoint;
    if (!cp.sessionId) throw notFound('That lab run’s session');
    return { run, cp, sessionId: cp.sessionId };
  };

  r.post('/messages/:id/lab', async (c) => {
    if (!deps.engine) throw labUnavailable();
    const m = await deps.repo.getMessage(c.req.param('id'));
    if (m?.role !== 'user') throw notFound('That message');
    const thread = await deps.repo.getThread(m.thread_id);
    if (!thread || thread.workspace_id !== deps.workspaceId) throw notFound('That thread');
    // Fast refusal; create() below is the atomic check.
    const live = (await deps.runs.activeForThread(thread.id))[0];
    if (live) throw alreadyRunning(live.id);
    const traceId = currentContext()?.traceId ?? newTraceId();
    const assistantId = `msg_${ulid()}`;
    const runId = `run_${ulid()}`;
    await deps.repo.insertMessage({
      id: assistantId,
      thread_id: thread.id,
      parent_id: m.id,
      role: 'assistant',
      parts: [],
      status: 'pending',
      run_id: runId,
      trace_id: traceId,
    });
    const checkpoint: LabCheckpoint = {
      v: 1,
      threadId: thread.id,
      workspaceId: thread.workspace_id,
      messageId: assistantId,
      prompt: textOf(m.parts),
      sessionId: null,
      promptMessageId: null,
    };
    try {
      await deps.runs.create({
        id: runId,
        kind: 'agent',
        traceId,
        threadId: thread.id,
        messageId: assistantId,
        checkpoint,
      });
    } catch (err) {
      // Another run took the thread a moment ago: leave no trace of this one.
      await deps.repo.discardMessages([assistantId]);
      throw err;
    }
    await deps.repo.patchThread(thread.id, { active_head_id: assistantId });
    deps.worker.kick();
    return c.json(
      {
        run_id: runId,
        user_message_id: m.id,
        assistant_message_id: assistantId,
        stream_url: `/api/v1/runs/${runId}/stream`,
      },
      202,
    );
  });

  r.get('/runs/:id/diff', async (c) => {
    const { run, cp } = await labRun(c.req.param('id'));
    const snap = snapshotDir(deps, run.id);
    if (!(await snapshotUsable(snap))) return c.json({ items: [], undo: false });
    return c.json({ items: await diffSnapshot(labPlace(deps, cp.threadId).realDir, snap), undo: true });
  });

  r.post('/runs/:id/undo', async (c) => {
    const { run, cp } = await labRun(c.req.param('id'));
    if (!['succeeded', 'failed', 'cancelled'].includes(run.status)) {
      throw new AncileError({
        code: 'run.already_running',
        title: 'This lab run is not finished yet',
        hint: 'Stop it or wait for it, then undo.',
        status: 409,
        errorClass: 'permanent',
      });
    }
    // Anything live in the thread may be writing to the same folder.
    const live = (await deps.runs.activeForThread(cp.threadId))[0];
    if (live) {
      throw new AncileError({
        code: 'run.already_running',
        title: 'This thread is still working',
        hint: 'Stop it or wait for it, then undo.',
        status: 409,
        errorClass: 'permanent',
        context: { run_id: live.id },
      });
    }
    // A later lab run built on these files: putting them back would undo it too.
    const labs = await deps.runs.forThread(cp.threadId, 'agent');
    const mine = labs.findIndex((l) => l.id === run.id);
    if (mine >= 0 && mine < labs.length - 1) {
      throw undoRefused(
        'lab.undo_superseded',
        'A later lab run changed these files',
        'Undo the latest lab run first, or undo nothing.',
      );
    }
    const message = await deps.repo.getMessage(cp.messageId);
    if (message?.provenance?.lab_undone_at || undoing.has(run.id)) {
      throw undoRefused('lab.already_undone', 'This lab run was already undone', 'Nothing more to put back.');
    }
    const snap = snapshotDir(deps, run.id);
    if (!(await snapshotUsable(snap))) {
      throw new AncileError({
        code: 'lab.undo_unavailable',
        title: "This lab run can't be undone",
        hint: 'Its folder was too large to copy before it started (over 50 MB, not counting dependencies).',
        status: 409,
        errorClass: 'permanent',
      });
    }
    undoing.add(run.id);
    try {
      const files = await restoreSnapshot(labPlace(deps, cp.threadId).realDir, snap);
      await deps.repo.updateMessage(cp.messageId, {
        provenance: { lab_undone_at: new Date().toISOString() },
      });
      return c.json({ run_id: run.id, undone: true, files });
    } finally {
      undoing.delete(run.id);
    }
  });

  return r;
}
