"""knowledge schema v1 (DESIGN.md §3.2)

Hand-written rather than autogenerated so the generated tsvector column, the
GIN index and the per-model vector index helper are explicit and reviewed.

Revision ID: 0001_init
Revises:
Create Date: 2026-10-07
"""

from alembic import op

revision = "0001_init"
down_revision = None
branch_labels = None
depends_on = None

S = "knowledge"


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {S}")

    op.execute(f"""
    CREATE TABLE {S}.sources (
      id              text PRIMARY KEY,
      workspace_id    text NOT NULL,
      kind            text NOT NULL CHECK (kind IN ('file','url','text','folder','thread','youtube','audio')),
      title           text NOT NULL,
      uri             text,
      mime            text,
      bytes           bigint,
      content_hash    text,
      status          text NOT NULL DEFAULT 'queued'
                      CHECK (status IN ('queued','extracting','enriching','embedding','ready','failed','stale')),
      progress        jsonb NOT NULL DEFAULT '{{}}',
      error           jsonb,
      tags            text[] NOT NULL DEFAULT '{{}}',
      topics          jsonb NOT NULL DEFAULT '{{}}',
      fetched_at      timestamptz,
      stale_after     timestamptz,
      etag            text,
      last_modified   text,
      current_version integer NOT NULL DEFAULT 0,
      created_at      timestamptz NOT NULL DEFAULT now(),
      updated_at      timestamptz NOT NULL DEFAULT now(),
      deleted_at      timestamptz
    )""")
    op.execute(f"CREATE INDEX sources_workspace ON {S}.sources (workspace_id) WHERE deleted_at IS NULL")
    op.execute(f"CREATE INDEX sources_hash ON {S}.sources (content_hash)")
    op.execute(f"CREATE INDEX sources_title_trgm ON {S}.sources USING gin (title gin_trgm_ops)")

    op.execute(f"""
    CREATE TABLE {S}.notebook_sources (
      notebook_id   text NOT NULL,
      source_id     text NOT NULL REFERENCES {S}.sources(id) ON DELETE CASCADE,
      context_level text NOT NULL DEFAULT 'full' CHECK (context_level IN ('off','insights','full')),
      added_at      timestamptz NOT NULL DEFAULT now(),
      PRIMARY KEY (notebook_id, source_id)
    )""")
    op.execute(f"CREATE INDEX notebook_sources_source ON {S}.notebook_sources (source_id)")

    op.execute(f"""
    CREATE TABLE {S}.source_versions (
      source_id     text NOT NULL REFERENCES {S}.sources(id) ON DELETE CASCADE,
      version       integer NOT NULL,
      markdown_path text NOT NULL,
      extractor     text NOT NULL,
      extracted_at  timestamptz NOT NULL DEFAULT now(),
      content_hash  text NOT NULL,
      PRIMARY KEY (source_id, version)
    )""")

    op.execute(f"""
    CREATE TABLE {S}.chunks (
      id            text PRIMARY KEY,
      source_id     text NOT NULL REFERENCES {S}.sources(id) ON DELETE CASCADE,
      version       integer NOT NULL,
      ordinal       integer NOT NULL,
      parent_id     text REFERENCES {S}.chunks(id) ON DELETE CASCADE,
      text          text NOT NULL,
      context_blurb text,
      heading_path  text[] NOT NULL DEFAULT '{{}}',
      page          integer,
      char_start    integer NOT NULL,
      char_end      integer NOT NULL CHECK (char_end > char_start),
      bbox          jsonb,
      tokens        integer NOT NULL,
      tsv           tsvector GENERATED ALWAYS AS
                    (to_tsvector('english', coalesce(context_blurb, '') || ' ' || text)) STORED,
      created_at    timestamptz NOT NULL DEFAULT now(),
      UNIQUE (source_id, version, ordinal)
    )""")
    op.execute(f"CREATE INDEX chunks_tsv_gin ON {S}.chunks USING gin (tsv)")
    op.execute(f"CREATE INDEX chunks_source ON {S}.chunks (source_id, version)")

    # Untyped vector: per-model partial HNSW indexes are created at runtime by
    # ancile_knowledge.db.hnsw_index_sql(model_key, dim) when a model is first used.
    op.execute(f"""
    CREATE TABLE {S}.chunk_embeddings (
      chunk_id  text NOT NULL REFERENCES {S}.chunks(id) ON DELETE CASCADE,
      model_key text NOT NULL,
      embedding vector NOT NULL,
      PRIMARY KEY (chunk_id, model_key)
    )""")

    op.execute(f"""
    CREATE TABLE {S}.transformations (
      id               text PRIMARY KEY,
      name             text NOT NULL UNIQUE,
      prompt_path      text NOT NULL,
      apply_on_ingest  boolean NOT NULL DEFAULT false,
      model_task_class text NOT NULL DEFAULT 'utility',
      created_at       timestamptz NOT NULL DEFAULT now()
    )""")

    op.execute(f"""
    CREATE TABLE {S}.insights (
      id                text PRIMARY KEY,
      source_id         text NOT NULL REFERENCES {S}.sources(id) ON DELETE CASCADE,
      transformation_id text NOT NULL REFERENCES {S}.transformations(id),
      content_md        text NOT NULL,
      model_id          text NOT NULL,
      created_at        timestamptz NOT NULL DEFAULT now()
    )""")
    op.execute(f"CREATE INDEX insights_source ON {S}.insights (source_id)")

    op.execute(f"""
    CREATE TABLE {S}.source_relations (
      a_id       text NOT NULL REFERENCES {S}.sources(id) ON DELETE CASCADE,
      b_id       text NOT NULL REFERENCES {S}.sources(id) ON DELETE CASCADE,
      kind       text NOT NULL CHECK (kind IN ('duplicate','near_duplicate','new_version')),
      score      real NOT NULL,
      status     text NOT NULL DEFAULT 'suggested' CHECK (status IN ('suggested','merged','dismissed')),
      created_at timestamptz NOT NULL DEFAULT now(),
      PRIMARY KEY (a_id, b_id),
      CHECK (a_id <> b_id)
    )""")


def downgrade() -> None:
    op.execute(f"DROP SCHEMA IF EXISTS {S} CASCADE")
